version: "2"

services:
  base:
    restart: always
    ports:
      - 9083:80
    image: clickzetta/base:1.0.0

  connector-api:
    restart: always
    network_mode: service:base
    image: clickzetta/connector-api:1.0.0
  
  prediction-api:
    restart: always
    network_mode: service:base
    image: clickzetta/prediction-api:1.0.0
